# Generated by Django 5.2.3 on 2025-07-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Privacy Policy', max_length=254)),
                ('content', models.TextField(help_text='The main text of the privacy policy')),
                ('pdf', models.FileField(blank=True, help_text='Upload a PDF version of the privacy policy (optional)', null=True, upload_to='privacy_policies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
