# Generated by Django 5.2.3 on 2025-07-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_returnspolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnspolicy',
            name='title',
            field=models.CharField(default='Returns Policy', max_length=254),
        ),
    ]
