# Generated by Django 5.2.3 on 2025-07-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=254)),
                ('email', models.EmailField(help_text="We'll use this email to respond to your inquiry.", max_length=254)),
                ('send_info', models.FileField(blank=True, help_text='Attach any relevant file (optional)', null=True, upload_to='contact_attachments/')),
                ('order_number', models.CharField(blank=True, help_text='Provide order number if you have one', max_length=100, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
