# Generated by Django 5.2.3 on 2025-07-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(upload_to='about/hero/')),
                ('overlay_title', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='NewArrivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_title', models.CharField(default='New Arrivals', max_length=254)),
                ('new_image', models.ImageField(upload_to='about/new_arrivals/')),
                ('new_name', models.CharField(max_length=100)),
                ('launched_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OurMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_mission_title', models.CharField(default='Our Mission', max_length=254)),
                ('our_mission_description', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='faqs',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='send_info',
            field=models.FileField(blank=True, null=True, upload_to='contact_attachments/'),
        ),
    ]
