# Generated by Django 5.2.3 on 2025-07-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_aboutpagehero_newarrivals_ourmission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Best Selling', max_length=254)),
                ('image', models.ImageField(upload_to='about/best_selling/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LaunchedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Launched Products', max_length=254)),
                ('image', models.ImageField(upload_to='about/launched/')),
                ('name', models.CharField(max_length=100)),
                ('launched_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OurMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Materials', max_length=254)),
                ('description', models.TextField()),
            ],
        ),
    ]
