# Generated by Django 5.2.3 on 2025-07-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_bestselling_launchedproducts_ourmaterials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestselling',
            old_name='description',
            new_name='best_description',
        ),
        migrations.RenameField(
            model_name='bestselling',
            old_name='image',
            new_name='best_image',
        ),
        migrations.RenameField(
            model_name='bestselling',
            old_name='title',
            new_name='best_selling_title',
        ),
        migrations.RenameField(
            model_name='launchedproducts',
            old_name='image',
            new_name='launched_image',
        ),
        migrations.RenameField(
            model_name='launchedproducts',
            old_name='name',
            new_name='launched_name',
        ),
        migrations.RenameField(
            model_name='launchedproducts',
            old_name='title',
            new_name='launched_title',
        ),
        migrations.RenameField(
            model_name='ourmaterials',
            old_name='description',
            new_name='our_materials_description',
        ),
        migrations.RenameField(
            model_name='ourmaterials',
            old_name='title',
            new_name='our_materials_title',
        ),
    ]
