# Generated by Django 5.2.3 on 2025-07-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_rename_description_bestselling_best_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpagehero',
            options={'verbose_name': 'About Page Hero', 'verbose_name_plural': 'About Page Hero'},
        ),
        migrations.AlterModelOptions(
            name='launchedproducts',
            options={'verbose_name_plural': 'Launched Products'},
        ),
        migrations.AlterModelOptions(
            name='newarrivals',
            options={'verbose_name_plural': 'New Arrivals'},
        ),
        migrations.AlterModelOptions(
            name='ourmaterials',
            options={'verbose_name_plural': 'Our Materials'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'Privacy Policies'},
        ),
        migrations.AlterModelOptions(
            name='returnspolicy',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'Returns Policies'},
        ),
        migrations.RemoveField(
            model_name='newarrivals',
            name='new_title',
        ),
    ]
