# Generated by Django 5.2.3 on 2025-07-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_aboutpagehero_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launchedproducts',
            name='launched_title',
        ),
        migrations.AlterField(
            model_name='bestselling',
            name='best_selling_title',
            field=models.CharField(max_length=254),
        ),
    ]
