# Generated by Django 5.2.3 on 2025-07-16 14:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_launchedproducts_launched_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagehero',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='About hero images'),
        ),
        migrations.AlterField(
            model_name='bestselling',
            name='best_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Best Sellling Products'),
        ),
        migrations.AlterField(
            model_name='launchedproducts',
            name='launched_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Launched images'),
        ),
        migrations.AlterField(
            model_name='newarrivals',
            name='new_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='New Arrivals'),
        ),
    ]
