# Generated by Django 4.2.16 on 2025-07-19 09:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_aboutpagehero_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagehero',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='bestselling',
            name='best_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='launchedproducts',
            name='launched_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='newarrivals',
            name='new_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='pdf',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a PDF version of the privacy policy (optional)', max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='returnspolicy',
            name='pdf',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a PDF version of the returns policy (optional)', max_length=255, null=True, verbose_name='file'),
        ),
    ]
