# Generated by Django 5.2.3 on 2025-07-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_sizes_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_size',
            field=models.BooleanField(default=False),
        ),
    ]
